config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  root to: 'pages#home'
  get 'search', to: 'pages#search', as: :search
  resources :cocktails, only: [:index, :show, :new, :create, :update] do
    collection do
      post 'autogenerate', to: 'cocktails#autogenerate', as: :autogenerate
    end
    resources :doses, only: :create
    resources :reviews, only: [:index, :create]
  end
  resources :doses, only: :destroy
  resources :ingredients, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
# == Schema Information
#
# Table name: cocktails
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  photo      :string
#

require 'faker'

class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader

  def self.search(search)
    if search
      where('name ILIKE ?', "%#{search}%")
    else
      []
    end
  end

  def self.generate_name
    Faker::Hipster.words(2).map { |el| el.capitalize if el[0] === el[0].downcase }.join(" ")
  end

  def self.generate_photo_url
    "https://source.unsplash.com/collection/2284026/1600x1200?#{rand(10000000000)}"
  end

  def self.best_rated
    all.select { |cocktail| cocktail.reviewed? }.sort_by { |cocktail| cocktail.rating }.reverse
  end

  def self.most_reviewed
    all.select { |cocktail| cocktail.reviewed? }.sort_by { |cocktail| cocktail.reviews.count }.reverse
  end

  def self.most_popular
    all.select { |cocktail| cocktail.reviewed? }.sort_by { |cocktail| cocktail.rank_score }.reverse
  end

  def self.not_reviewed
    all.reject { |cocktail| cocktail.reviewed? }
  end

  def rating
    return nil if reviews.count == 0

    (reviews.map { |review| review.rating }.reduce(:+) / reviews.count.to_f).round(1)
  end

  def rank_score
    rating * reviews.count
  end

  def reviewed?
    reviews.count != 0
  end
end

app/models/dose.rb
# == Schema Information
#
# Table name: doses
#
#  id            :bigint           not null, primary key
#  cocktail_id   :bigint
#  ingredient_id :bigint
#  description   :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, :uniqueness => { :scope => :cocktail }
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true

  def self.search(search)
    if search
      where('name ILIKE ?', "%#{search}%")
    else
      []
    end
  end

  def generate_photo_url
    "https://source.unsplash.com/1600x1200?#{name.split(' ').join(',')}"
  end
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id          :bigint           not null, primary key
#  rating      :integer          default(1)
#  description :text
#  cocktail_id :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Review < ApplicationRecord
  belongs_to :cocktail
  validates :description, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 5 }

  def self.most_relevant
    all.select { |cocktail| cocktail.reviewed? }.sort_by { |cocktail| cocktail.rank_score }.reverse
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :update]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
    @cocktail.remote_photo_url = Cocktail.generate_photo_url
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.remote_photo_url = params[:cocktail][:default_photo_url]
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def autogenerate
    @cocktail = Cocktail.new(name: Cocktail.generate_name)
    @cocktail.remote_photo_url = Cocktail.generate_photo_url
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  before_action :set_new_cocktail, only: [:create]

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      @show_edit_modal = true
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.new
    @new_cocktail = Cocktail.new
    @dose_to_destroy = Dose.find(params[:id])
    @cocktail = @dose_to_destroy.cocktail

    @dose_to_destroy.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def set_new_cocktail
    @new_cocktail = Cocktail.new
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_new_cocktail

  def home
    @cocktails = Cocktail.all
    @top_cocktails = Cocktail.best_rated
    @most_popular = Cocktail.most_popular
  end

  def search
    @keyword = (params[:search] || params[:home_search])[:keyword]
    @cocktails = Cocktail.search(@keyword)
    @ingredients = Ingredient.search(@keyword)
  end

  private

  def set_new_cocktail
    @new_cocktail = Cocktail.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail

  def index
    @reviews = @cocktail.reviews
    @review = Review.new
  end

  def create
    @dose = Dose.new
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_banner.html.erb
<div>
  <div class="banner position-relative" data-target="navbar.banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.id ? @cocktail.photo : @cocktail.remote_photo_url %>');">
    <a id="button-edit-photo" class="btn btn-outline-light" data-toggle="modal" data-target="#editPhoto">
      <i class="far fa-edit"></i> Edit photo
    </a>
    <div class="container d-flex justify-content-center flex-column h-100">
      <div>
        <h1><%= @cocktail.name %></h1>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/_card.html.erb
<div class="card-cocktail">
  <span><%= link_to cocktail.name, cocktail_path(cocktail) %></span>
  <div class="card-info px-3 d-flex align-content-center justify-content-end">
    <p class="m-0"><% if cocktail.rating %>
      <i class="fas fa-star"></i> <%=cocktail.rating %> <small>(<%=cocktail.reviews.count %>)</small>
      <% end %>
    </p>
    </div>
  <div class="card-cocktail-bg" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(cocktail.photo, width: 800, height: 600, crop: :fill) %>)"></div>
</div>

app/views/cocktails/_photo_upload_form.html.erb
<%= simple_form_for @cocktail, data: { controller: 'photo-upload' } do |f| %>
  <%= cl_image_tag @cocktail.photo, width: "300px", height: "200px", class: "m-3", data: { target: 'photo-upload.preview' } %>
  <%= f.input :photo, label: false, input_html: { data: { action: "change->photo-upload#afterUpload", target: 'photo-upload.realInput' } } %>
  <%= f.input :photo_cache, as: :hidden %>
  <!-- <div class="custom-file">
    <input type="file" class="custom-file-input" id="photo-upload" data-action="click->photo-upload#openBrowse" data-target="photo-upload.fileInput">
    <label class="custom-file-label" for="photo-upload" data-target="photo-upload.fileName">Choose file</label>
  </div> -->
  <%= f.submit "Upload", class: "btn btn-primary mt-3" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= 'https://source.unsplash.com/1600x900/?cocktail' %>');">
  <div class="container d-flex justify-content-center flex-column h-100">
    <div>
      <h1>All our cocktails</h1>
    </div>
  </div>
</div>


<div id="cocktails" class="container mt-5">

  <div class="grid-cards mb-5">
    <% @cocktails.each do |cocktail| %>
      <%= render partial: "cocktails/card", locals: { cocktail: cocktail } %>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="banner<%= ' vh-100' unless @cocktail.name && @cocktail.name != "" %>" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.id ? @cocktail.photo : @cocktail.remote_photo_url %>');">
  <div class="container d-flex justify-content-center flex-column h-100">
    <div>
      <% if @cocktail.name && @cocktail.name != "" %>
        <h1><%= @cocktail.name %></h1>
      <% else %>
        <%= simple_form_for @cocktail do |f| %>
          <div class="input-group justify-content-between" data-controller='new-cocktail'>
            <%= f.input :name, label: false, input_html: { data: { action: 'focus->new-cocktail#showBtn blur->new-cocktail#hideBtn' }, autocomplete: 'off' } %>
            <div class="input-group-append">
              <%= f.button :submit, "Create", id: 'create-cocktail-submit', class: 'btn-primary hidden', data: { target: 'new-cocktail.btnCreate' } %>
            </div>
          </div>
          <%= f.input :default_photo_url, as: :hidden, input_html: { value: @cocktail.remote_photo_url } %>
          <div class="row">
            <p class="text-center mt-3 w-100">OR</p>
            <%= link_to "Auto-generate name", autogenerate_cocktails_path, method: :post, id:"btn-autogenerate-name", class: "btn btn-outline-light mt-3 mx-auto" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<%= render 'banner' %>

<div class="container mb-5">
  <div id="container-ingredients" class="container hoverable">
    <div class="row pt-5 justify-content-center">
      <div class="col-12 col-sm-8">
        <h3>Ingredients</h3>
        <% if @cocktail.doses.size > 0 %>
          <a href="#" class="btn btn-outline-secondary btn-hover-container" data-toggle="modal" data-target="#editIngredients">
            <i class="far fa-edit"></i> Edit recipe
          </a>
          <ul class="list-ingredients list-group">
            <% @cocktail.doses.each do |dose| %>
              <li class="list-group-item"><%= dose.description %> of <%= dose.ingredient.name %></li>
            <% end %>
          </ul>
        <% else %>
          <p>No ingredients in this cocktail recipe yet...</p>
          <a id="add-first-ingredient" class="btn btn-outline-secondary" data-toggle="modal" data-target="#editIngredients">
            <i class="far fa-edit"></i> Add your first ingredient
          </a>
        <% end %>
      </div>
    </div>
  </div>

  <div id="container-reviews" class="container hoverable">
    <div class="row pt-5 justify-content-center">
      <div class="col-12 col-sm-8">
        <h3>Reviews</h3>
        <% if @cocktail.reviews.size > 0 %>
          <a href="#leave-a-review" class="btn btn-outline-secondary btn-hover-container">
            <i class="fas fa-star"></i> Leave a review
          </a>
          <ul class="list-ingredients list-group">
            <% @cocktail.reviews.take(8).each do |review| %>
              <li class="list-group-item">
                <%= ('<i class="fas fa-star"></i>' * review.rating).html_safe %>
                <p><%= review.description %></p>
                </li>
            <% end %>
          </ul>
          <% if @cocktail.reviews.count > 8 %>
            <div class="text-center"><%= link_to "See all reviews for #{@cocktail.name}", cocktail_reviews_path(@cocktail) %></div>
          <% end %>
        <% else %>
          <p>No reviews for this cocktail yet...</p>
        <% end %>
        <%= render 'reviews/form' %>
      </div>
    </div>
  </div>
</div>


<!-- New Ingredient Modal -->
<div class="modal fade" id="editIngredients" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit recipe for <%= @cocktail.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "doses/list_edit" %>
        <%= render "doses/form" %>
      </div>
    </div>
  </div>
</div>

<!-- Edit Photo Modal -->
<div class="modal fade" id="editPhoto" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Upload photo for <%= @cocktail.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <%= render "cocktails/photo_upload_form" %>
      </div>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<h5>Add an ingredient</h5>
<%= simple_form_for [@cocktail, @dose], wrapper: :horizontal_form, html: { data: { controller: 'select2' } } do |f| %>
  <%= f.association :ingredient, input_html:  { class: "select2", style: "width: 100%;" } %>
  <%= f.input :description, placeholder: "e.g. 20 mL, 3 parts" %>
  <%= f.submit "Add this ingredient", class: "nav-link btn btn-primary" %>
<% end %>

app/views/doses/_list_edit.html.erb
<h3>Ingredients</h3>
<% if @cocktail.doses.size > 0 %>
  <ul class="list-ingredients">
    <% @cocktail.doses.each do |dose| %>
      <li class="d-flex justify-content-between mx-auto w-75"><span><%= dose.description %> of <%= dose.ingredient.name %></span> <a data-toggle="modal" data-target="#deleteIngredient<%= dose.id %>"><i class="far fa-trash-alt"></i></a></li>
    <% end %>
  </ul>
<% else %>
  <p>No ingredients in this cocktail recipe yet...</p>
<% end %>

<% @cocktail.doses.each do |dose| %>
  <!-- Delete Ingredient Modal -->
  <div class="modal fade" id="deleteIngredient<%= dose.id %>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Remove ingredient?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to remove <%= dose.ingredient.name %> from <%= @cocktail.name %>?</p>
          <%= link_to "Remove", dose_path(dose), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/ingredients/_card.html.erb
<div class="card-cocktail">
  <span><%= link_to ingredient.name, ingredient_path(ingredient) %></span>
  <div class="card-cocktail-bg" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= ingredient.generate_photo_url %>)"></div>
</div>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= 'https://source.unsplash.com/1600x900/?cocktail' %>');">
  <div class="container d-flex justify-content-center flex-column h-100">
    <div>
      <h1>Search results for <%= @keyword %></h1>
      <%= simple_form_for :search, wrapper: :inline_form, html: { id: 'new-search-form', class: 'form-inline' }, url: search_path, method: :get do |f| %>
          <%= f.input :keyword, label: false, style: "width: 50%", input_html: { value: @keyword, placeholder: @keyword } %>
          <%= f.button :submit, "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Cocktails</h2>
      <div class="grid-cards mb-5">
        <% @cocktails.each do |cocktail| %>
          <%= render partial: "cocktails/card", locals: { cocktail: cocktail } %>
        <% end %>
      </div>

      <h2>Ingredients</h2>
      <div class="grid-cards mb-5">
        <% @ingredients.each do |ingredient| %>
          <%= render partial: "ingredients/card", locals: { ingredient: ingredient } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HipsterBlends🍸</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="main-content" data-controller="navbar" data-action="scroll@window->navbar#toggleBackground">
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="main-banner" class="banner">
  <div class="container d-flex justify-content-center flex-column h-100" data-target="navbar.banner">
    <div>
      <!-- <span class="logo">HipsterBlends <i class="fas fa-cocktail"></i></span> -->
      <h1 class="my-3">The world's best hipster cocktail recipes.</h1>
      <p class="my-3">Because alcohol tastes better than tears.</p>

      <%= simple_form_for :home_search, wrapper: :inline_form, html: { id: 'search-form', class: 'form-inline my-5', data: { controller: 'home' } }, url: search_path, method: :get do |f| %>
          <%= f.input :keyword, label: false, wrapper_html: { class: 'flex-grow-1' }, input_html: { class: 'w-100' } %>
          <%= f.button :submit, "Find the perfect drink", class: "btn-primary" %>
      <% end %>
    </div>
  </div>
</div>


<div id="cocktails" class="container mt-5">
  <h2>Most popular</h2>
  <div class="grid-cards mb-5">
    <% @most_popular.take(4).each do |cocktail| %>
      <%= render partial: "cocktails/card", locals: { cocktail: cocktail } %>
    <% end %>
  </div>

  <h2>All our cocktails</h2>
  <div class="grid-cards mb-5">
    <% @cocktails.each do |cocktail| %>
      <%= render partial: "cocktails/card", locals: { cocktail: cocktail } %>
    <% end %>
  </div>
</div>

app/views/pages/search.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= 'https://source.unsplash.com/1600x900/?cocktail' %>');">
  <div class="container d-flex justify-content-center flex-column h-100">
    <div>
      <h1>Search results for <%= @keyword %></h1>
      <%= simple_form_for :search, wrapper: :inline_form, html: { id: 'new-search-form', class: 'form-inline' }, url: search_path, method: :get do |f| %>
          <%= f.input :keyword, label: false, style: "width: 50%", placeholder: @keyword %>
          <%= f.button :submit, "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Cocktails</h2>
      <div class="grid-cocktails mb-5">
        <% @cocktails.each do |cocktail| %>
          <%= render partial: "cocktails/card", locals: { cocktail: cocktail } %>
        <% end %>
      </div>

      <h2>Ingredients</h2>
      <div class="grid-cocktails mb-5">
        <% @ingredients.each do |ingredient| %>
          <%= render partial: "cocktails/card", locals: { cocktail: ingredient } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<div id="leave-a-review" class="form-leave-review mt-5">
  <h5>Leave a review</h5>
  <%= simple_form_for [@cocktail, @review], wrapper: :horizontal_form do |f| %>
    <%= f.input :rating, input_html: { min: 1, max: 5 }, placeholder: 'Rate this cocktail from 1 to 5' %>
    <%= f.input :description, placeholder: "What did you like or dislike about this cocktail?" %>
    <%= f.submit "Submit review", class: "nav-link btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<%= render 'cocktails/banner' %>

<div id="container-reviews" class="container">
  <div class="row pt-5 justify-content-center">
    <div class="col-12 col-sm-8">
      <h3>All reviews for <%= link_to @cocktail.name, cocktail_path(@cocktail) %></h3>
      <% if @cocktail.reviews.size > 0 %>
        <a id="button-add-ingredient" class="btn btn-outline-secondary" data-toggle="modal" data-target="#editIngredients">
          <i class="fas fa-star"></i> Leave a review
        </a>
        <ul class="list-ingredients list-group">
          <% @cocktail.reviews.each do |review| %>
            <li class="list-group-item">
              <%= ('<i class="fas fa-star"></i>' * review.rating).html_safe %>
              <p><%= review.description %></p>
              </li>
          <% end %>
        </ul>
      <% else %>
        <p>No reviews for this cocktail yet...</p>
      <% end %>
      <%= render 'reviews/form' %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer" class="row bg-secondary vh-10 justify-content-center align-content-end">
  <%= link_to root_path, class: "navbar-brand text-white" do %>
    <span class="logo small">HipsterBlends <i class="fas fa-cocktail"></i></span>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-hipsterblends fixed-top" data-target="navbar.navbar">
  <%= link_to root_path, class: "navbar-brand text-white" do %>
    <span class="logo">HipsterBlends <i class="fas fa-cocktail"></i></span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Browse", cocktails_path, class: "btn btn-outline-light mr-3" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktail", new_cocktail_path, class: "btn btn-primary mr-3" %>
      </li>
    </ul>
  </div>
</div>